---
apiVersion: apps/V1
kind: Deployment
metadata:
   name: my-Dev
   labels:
      app: android
      env: dev
spec: 
  replicas: 10
  strategy:
       type: Rollingupdate
	   rollingupdate:
	       maxsurge: 1
		   maxunavilable: 1
  template:
       metadata: 
         labels:
           app: android
	   env: dev
	spec:
          containers:
          - name: nginx-app
            image: 'aksdevopsacr.azurecr.io/app1nginxaks:latest'
            ports:
            - containerport: 8080	
            resources:
              requests:
                cpu: "500m"
                memory: "50Gi"						 
              limits:
                cpu: "1000m"
                memory: "100Gi"
						 
------

apiVersion: v1
kind: service
metadata:
    name: myservice
spec:
  type: NodePort
  selector:
     matchlabels:
         myapp: android
	 env: dev
  ports:
  - port: 80
    targetport: 8080
    NodePort: 31000
		 
			 
